<a href="https://colab.research.google.com/github/pennya6/AI_study/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5/%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling

In [ ]:
md=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/기계학습/DataPreprocessing.csv")

In [ ]:
md

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [ ]:
X=md.iloc[:,:-1].values
Y=md.iloc[:,-1].values

In [ ]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, nan],
       ['India', 40.0, 69600.0],
       ['Brazil', nan, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [ ]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#평균값으로 nan을 대체하겠다
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:,1:]) #인덱스 1부터 끝까지
X[:,1:]=imputer.transform(X[:,1:])

In [ ]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [ ]:
#Handling of categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()

In [ ]:
X[:,0]=labelencoder_X.fit_transform(X[:,0])

In [ ]:
X[:,0]

array([1, 0, 2, 0, 2, 1, 0, 1, 2, 1], dtype=object)

In [ ]:
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [ ]:
#minmaxscale
from sklearn.preprocessing import MinMaxScaler

In [ ]:
minmax_scaler=MinMaxScaler()


In [ ]:
X=minmax_scaler.fit_transform(X)

In [ ]:
X

array([[0.5       , 0.73913043, 0.68571429],
       [0.        , 0.        , 0.        ],
       [1.        , 0.13043478, 0.17142857],
       [0.        , 0.47826087, 0.37142857],
       [1.        , 0.56521739, 0.45079365],
       [0.5       , 0.34782609, 0.28571429],
       [0.        , 0.51207729, 0.11428571],
       [0.5       , 0.91304348, 0.88571429],
       [1.        , 1.        , 1.        ],
       [0.5       , 0.43478261, 0.54285714]])